package hogwarts;

import java.awt.CardLayout;

/**
 *
 * @author Henric Berg and Peter Karlsson
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Detta gränssnitt är startsidan. Detta är det första som användaren ser när programmet startas.
     * Här väljer man inloggningsmetod (Lärare/Elev/Admin/Ingen Användare)
     * 
     */
    
    public Welcome() { //Konstruktorn initialiserar 'standard' layouten. Detta görs via en CardLayout.
        initComponents();
        CardLayout card = (CardLayout) pnlPassword.getLayout(); //En cardlayout är en layout-hanterare som endast visar en 'container' åt gången.
        card.show(pnlPassword, "pnlBlank");                     //I detta fall så visar den en tom container precis under elev/lärar-knapparna.
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblChoice = new javax.swing.JLabel();
        btnStudent = new javax.swing.JButton();
        btnTeacher = new javax.swing.JButton();
        lblNotLoggedIn = new javax.swing.JLabel();
        btnNotLoggedIn = new javax.swing.JButton();
        pnlPassword = new javax.swing.JPanel();
        pnlShowPassword = new javax.swing.JPanel();
        lblPasswordRequest = new javax.swing.JLabel();
        btnLogIn = new javax.swing.JButton();
        ckbxAdmin = new javax.swing.JCheckBox();
        pwdPassword = new javax.swing.JPasswordField();
        pnlBlank = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblWelcome.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Välkommen till Hogwarts");

        lblChoice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblChoice.setText("Vad vill du logga in som?");

        btnStudent.setText("Elev");
        btnStudent.setPreferredSize(new java.awt.Dimension(100, 50));
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });

        btnTeacher.setText("Lärare");
        btnTeacher.setPreferredSize(new java.awt.Dimension(100, 50));
        btnTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherActionPerformed(evt);
            }
        });

        lblNotLoggedIn.setText("Har du ingen användare...");

        btnNotLoggedIn.setText("Tryck här!");
        btnNotLoggedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotLoggedInActionPerformed(evt);
            }
        });

        pnlPassword.setLayout(new java.awt.CardLayout());

        lblPasswordRequest.setText("Ange lösenord:");

        btnLogIn.setText("Logga in");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        ckbxAdmin.setText("Logga in som Administratör");

        javax.swing.GroupLayout pnlShowPasswordLayout = new javax.swing.GroupLayout(pnlShowPassword);
        pnlShowPassword.setLayout(pnlShowPasswordLayout);
        pnlShowPasswordLayout.setHorizontalGroup(
            pnlShowPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlShowPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlShowPasswordLayout.createSequentialGroup()
                        .addComponent(ckbxAdmin)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlShowPasswordLayout.createSequentialGroup()
                        .addComponent(lblPasswordRequest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogIn)))
                .addContainerGap())
        );
        pnlShowPasswordLayout.setVerticalGroup(
            pnlShowPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowPasswordLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlShowPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogIn)
                    .addComponent(lblPasswordRequest)
                    .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbxAdmin)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnlPassword.add(pnlShowPassword, "pnlShowPassword");

        javax.swing.GroupLayout pnlBlankLayout = new javax.swing.GroupLayout(pnlBlank);
        pnlBlank.setLayout(pnlBlankLayout);
        pnlBlankLayout.setHorizontalGroup(
            pnlBlankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
        pnlBlankLayout.setVerticalGroup(
            pnlBlankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlPassword.add(pnlBlank, "pnlBlank");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 141, Short.MAX_VALUE)
                .addComponent(lblWelcome)
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(lblChoice))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNotLoggedIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNotLoggedIn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome)
                .addGap(129, 129, 129)
                .addComponent(lblChoice)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNotLoggedIn)
                    .addComponent(btnNotLoggedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed

        Start.studentActions(); //Ber start-klassen att initalisera elev-gränssnittet.
        dispose();  //Stänger startsidan

    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherActionPerformed
        CardLayout card = (CardLayout) pnlPassword.getLayout();
        card.show(pnlPassword, "pnlShowPassword"); //Visar containern som innehåller lösenords-input för lärare/admin precis nedanför knapparna.
        
    }//GEN-LAST:event_btnTeacherActionPerformed

    private void btnNotLoggedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotLoggedInActionPerformed
        Start.studentActions(); //Ber start-klassen att initalisera ej användare-gränssnittet. (Samma som elev)
        dispose();
    }//GEN-LAST:event_btnNotLoggedInActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        if (Validate.firstPageLogIn(pwdPassword, ckbxAdmin)) //Ber Validate-klassen att kontrollera lösenord samt admin-status.
        {
            dispose();
        }            
        
    }//GEN-LAST:event_btnLogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnNotLoggedIn;
    private javax.swing.JButton btnStudent;
    private javax.swing.JButton btnTeacher;
    private javax.swing.JCheckBox ckbxAdmin;
    private javax.swing.JLabel lblChoice;
    private javax.swing.JLabel lblNotLoggedIn;
    private javax.swing.JLabel lblPasswordRequest;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlBlank;
    private javax.swing.JPanel pnlPassword;
    private javax.swing.JPanel pnlShowPassword;
    private javax.swing.JPasswordField pwdPassword;
    // End of variables declaration//GEN-END:variables
}
