/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import grupp1.Database;
import grupp1.Person;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.*;
import java.util.Calendar;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.*;

/**
 *
 * @author Nötfärs
 */
public class HemGUI extends javax.swing.JFrame {

    private Person inloggadPerson;

    public HemGUI(Person inloggadPerson) {
        initComponents();
        this.inloggadPerson = inloggadPerson;
        Calendar cal = Calendar.getInstance();
        lblDatum.setText("Startsida - Dagens datum är: " + cal.getTime().toString());
        uppdateraDatum();
        setIngressText(1, txtPnlInlagg1);
                setIngressText(2, txtPnlInlagg2);
                        setIngressText(3, txtPnlInlagg3);
                                                setIngressText(4, txtPnlInlagg4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlMeny = new javax.swing.JPanel();
        btnHem = new javax.swing.JButton();
        btnUtbildning = new javax.swing.JButton();
        btnForskning = new javax.swing.JButton();
        btnProfil = new javax.swing.JButton();
        lblDatum = new javax.swing.JLabel();
        pnlMeny2 = new javax.swing.JPanel();
        btnStartsida = new javax.swing.JButton();
        btnSkapaInlagg = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        pnlTextArea = new javax.swing.JPanel();
        pnlIngress = new javax.swing.JPanel();
        scrPnlTextPane1 = new javax.swing.JScrollPane();
        txtPnlInlagg1 = new javax.swing.JTextPane();
        scrPnlTextPane2 = new javax.swing.JScrollPane();
        txtPnlInlagg2 = new javax.swing.JTextPane();
        scrPnlTextPane3 = new javax.swing.JScrollPane();
        txtPnlInlagg3 = new javax.swing.JTextPane();
        scrPnlTextPane4 = new javax.swing.JScrollPane();
        txtPnlInlagg4 = new javax.swing.JTextPane();
        pnlHeltext = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));

        btnHem.setBackground(new java.awt.Color(255, 255, 255));
        btnHem.setText("Hem");

        btnUtbildning.setBackground(new java.awt.Color(255, 255, 255));
        btnUtbildning.setText("Utbildning");
        btnUtbildning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtbildningActionPerformed(evt);
            }
        });

        btnForskning.setBackground(new java.awt.Color(255, 255, 255));
        btnForskning.setText("Forskning");
        btnForskning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForskningActionPerformed(evt);
            }
        });

        btnProfil.setBackground(new java.awt.Color(255, 255, 255));
        btnProfil.setText("Profil");
        btnProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenyLayout = new javax.swing.GroupLayout(pnlMeny);
        pnlMeny.setLayout(pnlMenyLayout);
        pnlMenyLayout.setHorizontalGroup(
            pnlMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHem, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUtbildning, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnForskning, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenyLayout.setVerticalGroup(
            pnlMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfil)
                    .addComponent(btnForskning)
                    .addComponent(btnUtbildning)
                    .addComponent(btnHem)
                    .addComponent(lblDatum))
                .addContainerGap())
        );

        btnStartsida.setBackground(new java.awt.Color(255, 255, 255));
        btnStartsida.setText("Startsida");
        btnStartsida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartsidaActionPerformed(evt);
            }
        });

        btnSkapaInlagg.setBackground(new java.awt.Color(255, 255, 255));
        btnSkapaInlagg.setText("Skapa inlägg");
        btnSkapaInlagg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaInlaggActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Logga ut");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMeny2Layout = new javax.swing.GroupLayout(pnlMeny2);
        pnlMeny2.setLayout(pnlMeny2Layout);
        pnlMeny2Layout.setHorizontalGroup(
            pnlMeny2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMeny2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMeny2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSkapaInlagg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStartsida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMeny2Layout.setVerticalGroup(
            pnlMeny2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMeny2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStartsida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSkapaInlagg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );

        pnlTextArea.setLayout(new java.awt.CardLayout());

        txtPnlInlagg1.setEditable(false);
        txtPnlInlagg1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrPnlTextPane1.setViewportView(txtPnlInlagg1);

        txtPnlInlagg2.setEditable(false);
        txtPnlInlagg2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrPnlTextPane2.setViewportView(txtPnlInlagg2);

        txtPnlInlagg3.setEditable(false);
        txtPnlInlagg3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrPnlTextPane3.setViewportView(txtPnlInlagg3);

        txtPnlInlagg4.setEditable(false);
        txtPnlInlagg4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrPnlTextPane4.setViewportView(txtPnlInlagg4);

        javax.swing.GroupLayout pnlIngressLayout = new javax.swing.GroupLayout(pnlIngress);
        pnlIngress.setLayout(pnlIngressLayout);
        pnlIngressLayout.setHorizontalGroup(
            pnlIngressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIngressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrPnlTextPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrPnlTextPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(pnlIngressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrPnlTextPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrPnlTextPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlIngressLayout.setVerticalGroup(
            pnlIngressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngressLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlIngressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrPnlTextPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrPnlTextPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(pnlIngressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrPnlTextPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrPnlTextPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pnlTextArea.add(pnlIngress, "card5");

        javax.swing.GroupLayout pnlHeltextLayout = new javax.swing.GroupLayout(pnlHeltext);
        pnlHeltext.setLayout(pnlHeltextLayout);
        pnlHeltextLayout.setHorizontalGroup(
            pnlHeltextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        pnlHeltextLayout.setVerticalGroup(
            pnlHeltextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        pnlTextArea.add(pnlHeltext, "card3");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlMeny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(pnlMeny2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMeny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMeny2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilActionPerformed

        ProfilGUI pGUI = new ProfilGUI(inloggadPerson);
        pGUI.setVisible(true);

//        try {
//            Connection con = Database.getDB();
//            Statement stmt = con.createStatement();
//            String sql = "SELECT * FROM namn";
//            ResultSet rs = stmt.executeQuery(sql);
//            String p = "";
//            
//            while (rs.next()) {
//                p = p + "ID: " + rs.getInt("ID") + " - Namn: " + rs.getString("fornamn") + " " + rs.getString("efternamn") + "\n";
//                jTextArea1.setText(p);
//            }
//        } catch (SQLException error) {
//            System.out.println(error.getMessage());
//        }
    }//GEN-LAST:event_btnProfilActionPerformed

    private void btnStartsidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartsidaActionPerformed

    }//GEN-LAST:event_btnStartsidaActionPerformed

    private void btnSkapaInlaggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaInlaggActionPerformed
        InlaggGUI inlagg = new InlaggGUI(inloggadPerson);
        inlagg.setVisible(true);
    }//GEN-LAST:event_btnSkapaInlaggActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        LoginGUI login1 = new LoginGUI();
        login1.setVisible(true);
        login1.setLocationRelativeTo(null);
        dispose();
        try {
            File currentDirectory = new File("");
            String mp3 = currentDirectory.getAbsolutePath() + "\\login.wav";
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(new File(mp3));
            Clip clip = AudioSystem.getClip();
            clip.open(audioIn);
            clip.start();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnForskningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForskningActionPerformed

    }//GEN-LAST:event_btnForskningActionPerformed

    private void btnUtbildningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtbildningActionPerformed
        
        
    }//GEN-LAST:event_btnUtbildningActionPerformed
    public void uppdateraDatum() {
        ActionListener uppgift = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                Calendar cal = Calendar.getInstance();
                lblDatum.setText("Visar: Startsida - Dagens datum är: " + cal.getTime().toString());

            }
        };
        new Timer(1000, uppgift).start();
    }

    public void setIngressText(int tick, JTextPane txtPanel) {
        int i = 0;
        try {
            ResultSet inlagg = Database.sqlSelect("SELECT * FROM INLAGG");
            while (inlagg.next() && i < tick) {

                String rubrik = inlagg.getString("RUBRIK");
                String ingress = inlagg.getString("INGRESS");
                String datum = inlagg.getString("DATUM");
                txtPanel.setText(rubrik + "\n" + ingress + "\n" + datum);
                i++;
            }
        } catch (Exception e) {

        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnForskning;
    private javax.swing.JButton btnHem;
    private javax.swing.JButton btnProfil;
    private javax.swing.JButton btnSkapaInlagg;
    private javax.swing.JButton btnStartsida;
    private javax.swing.JButton btnUtbildning;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JPanel pnlHeltext;
    private javax.swing.JPanel pnlIngress;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMeny;
    private javax.swing.JPanel pnlMeny2;
    private javax.swing.JPanel pnlTextArea;
    private javax.swing.JScrollPane scrPnlTextPane1;
    private javax.swing.JScrollPane scrPnlTextPane2;
    private javax.swing.JScrollPane scrPnlTextPane3;
    private javax.swing.JScrollPane scrPnlTextPane4;
    private javax.swing.JTextPane txtPnlInlagg1;
    private javax.swing.JTextPane txtPnlInlagg2;
    private javax.swing.JTextPane txtPnlInlagg3;
    private javax.swing.JTextPane txtPnlInlagg4;
    // End of variables declaration//GEN-END:variables
}
