/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Font;
import grupp1.Database;
import grupp1.Person;

/**
 *
 * @author malin
 */
public class InlaggGUI extends javax.swing.JFrame {
private Person personen;
    /**
     * Creates new form Inlagg
     */
    public InlaggGUI(Person personen) {
        this.personen = personen;
        initComponents();

        //Lägga in dessa + fler i databasen istället?
        cbFont.addItem("Monospaced");
        cbFont.addItem("Arial");
        cbStorlek.addItem("11");
        cbStorlek.addItem("16");
        cbKategori.addItem("Utbildning");
        cbKategori.addItem("Forskning");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taInlagg = new javax.swing.JTextArea();
        tfRubrik = new javax.swing.JTextField();
        btnPublicera = new javax.swing.JButton();
        cbKategori = new javax.swing.JComboBox<>();
        cbFont = new javax.swing.JComboBox<>();
        cbStorlek = new javax.swing.JComboBox<>();
        btnBold = new javax.swing.JToggleButton();
        btnItalic = new javax.swing.JToggleButton();
        btnAndra = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        taInlagg.setColumns(20);
        taInlagg.setRows(5);
        jScrollPane1.setViewportView(taInlagg);

        tfRubrik.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfRubrik.setText("Rubrik");
        tfRubrik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfRubrikMouseClicked(evt);
            }
        });

        btnPublicera.setText("Publicera");
        btnPublicera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPubliceraActionPerformed(evt);
            }
        });

        btnBold.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBold.setText("B");
        btnBold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoldActionPerformed(evt);
            }
        });

        btnItalic.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        btnItalic.setText("I");
        btnItalic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItalicActionPerformed(evt);
            }
        });

        btnAndra.setText("Ändra");
        btnAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraActionPerformed(evt);
            }
        });

        btnExit.setText("Huvudmeny");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnExit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(btnPublicera, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(cbFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(cbStorlek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnAndra)
                        .addGap(28, 28, 28)
                        .addComponent(btnBold)
                        .addGap(18, 18, 18)
                        .addComponent(btnItalic)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnItalic)
                                    .addComponent(btnBold)
                                    .addComponent(cbStorlek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAndra))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit)))
                    .addComponent(btnPublicera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//Måste ändra både font och storlek samtidigt just nu vilket innebär att det 
//måste finnas en "ändra" knapp 
//allting i textarean ändras, vill att bara selected text ska ändras
    private void btnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraActionPerformed

        String font = (String) cbFont.getSelectedItem();
        String fontStorlek = (String) cbStorlek.getSelectedItem();
        int storlek2 = Integer.parseInt(fontStorlek);

        Font myFont = new Font(font, Font.PLAIN, storlek2);

        taInlagg.setFont(myFont);
    }//GEN-LAST:event_btnAndraActionPerformed
//Just nu kan texten inte vara bold och italic samtidigt 
//och allting i textarean blir fetstil

    private void btnBoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoldActionPerformed

        if (btnBold.isSelected()) {
            taInlagg.setFont(taInlagg.getFont().deriveFont(Font.BOLD));

        } else {
            taInlagg.setFont(taInlagg.getFont().deriveFont(Font.PLAIN)); //istället för plain, typ "not bold"? För om man valt kursivt ska det vara kvar
        }                                                                //och vice versa

    }//GEN-LAST:event_btnBoldActionPerformed
    //Just nu kan texten inte vara bold och italic samtidigt 
    //och allting i textarean blir kursivt
    private void btnItalicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItalicActionPerformed

        if (btnItalic.isSelected()) {
            taInlagg.setFont(taInlagg.getFont().deriveFont(Font.ITALIC));

        } else {
            taInlagg.setFont(taInlagg.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_btnItalicActionPerformed

    private void tfRubrikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfRubrikMouseClicked
    tfRubrik.setText(null);
    }//GEN-LAST:event_tfRubrikMouseClicked

    private void btnPubliceraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPubliceraActionPerformed
    //        String rubrik = tfRubrik.getText();
//        String inlaggText = taInlagg.getText();
//        String kategori = (String) cbKategori.getSelectedItem();
//        String ingress = inlaggText.substring(0, 100) + "...";
//        String datum = "2017-01-27"; //dagens datum
//        String inlaggId = "1"; //ska ske med autoIncrement
//        String forfattare = "30"; //ska ju vara id för inloggad användare

//        try {

////          String id = Database.getAutoIncrement("inlagg", "inlaggid"); //Ger inlägget nästa lediga id för inlägg
//            Database.insert("insert into inlagg (inlaggid, rubrik, ingress, heltext, datum, forfattare) values "
//                    + "('" + inlaggId + "'," + "'" + rubrik + "'," + "'" + ingress + "'," + "'" + inlaggText + "'" + "," + " '" + datum + "'" + "," + "'" + forfattare + ")");
//            JOptionPane.showMessageDialog(null, "Inlägget har publicerats");
//
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(null, "Någonting gick fel!");
//
//        }
    }//GEN-LAST:event_btnPubliceraActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
            HemGUI hem = new HemGUI(personen);
            hem.setVisible(true);
            hem.setLocationRelativeTo(null);
            dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndra;
    private javax.swing.JToggleButton btnBold;
    private javax.swing.JButton btnExit;
    private javax.swing.JToggleButton btnItalic;
    private javax.swing.JButton btnPublicera;
    private javax.swing.JComboBox<String> cbFont;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JComboBox<String> cbStorlek;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taInlagg;
    private javax.swing.JTextField tfRubrik;
    // End of variables declaration//GEN-END:variables
}
