/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Font;
import grupp1.Database;
import grupp1.Person;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author malin
 */
public class InlaggGUI extends javax.swing.JFrame {

    private Person inloggadPerson;

    /**
     * Creates new form Inlagg
     */
    public InlaggGUI(Person inloggadPerson) {
        this.inloggadPerson = inloggadPerson;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        tfRubrik = new javax.swing.JTextField();
        btnPublicera = new javax.swing.JButton();
        cbKategori = new javax.swing.JComboBox<>();
        cbFont = new javax.swing.JComboBox<>();
        cbStorlek = new javax.swing.JComboBox<>();
        btnBold = new javax.swing.JToggleButton();
        btnItalic = new javax.swing.JToggleButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpInlagg = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        tfRubrik.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfRubrik.setText("Rubrik");
        tfRubrik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfRubrikMouseClicked(evt);
            }
        });

        btnPublicera.setBackground(new java.awt.Color(255, 255, 255));
        btnPublicera.setText("Publicera");
        btnPublicera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPubliceraActionPerformed(evt);
            }
        });

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Utbildning", "Forskning" }));

        cbFont.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arial", "Book Antiqua", "Calibri", "Garamond", "Georgia", "Monospace", "Verdana", "Tahoma", "Times New Roman" }));
        cbFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFontActionPerformed(evt);
            }
        });

        cbStorlek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "10", "12", "14", "18", "24", "32", "36", "48" }));
        cbStorlek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStorlekActionPerformed(evt);
            }
        });

        btnBold.setBackground(new java.awt.Color(255, 255, 255));
        btnBold.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBold.setText("B");
        btnBold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoldActionPerformed(evt);
            }
        });

        btnItalic.setBackground(new java.awt.Color(255, 255, 255));
        btnItalic.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        btnItalic.setText("I");
        btnItalic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItalicActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Huvudmeny");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(tpInlagg);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(btnExit)
                        .addGap(405, 405, 405)
                        .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMainLayout.createSequentialGroup()
                            .addComponent(tfRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(cbFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cbStorlek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnBold)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnItalic))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnPublicera, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addComponent(tfRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbStorlek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBold)
                            .addComponent(btnItalic))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPublicera, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMain, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

///Just nu kan texten inte vara bold och italic samtidigt 
//och allting i textarean blir fetstil

    private void btnBoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoldActionPerformed

        if (btnBold.isSelected()) {
            tpInlagg.setFont(tpInlagg.getFont().deriveFont(Font.BOLD));
         

            } else {
                tpInlagg.setFont(tpInlagg.getFont().deriveFont(Font.PLAIN)); //istället för plain, typ "not bold"? För om man valt kursivt ska det vara kvar
            }                                                                //och vice versa
        
    }//GEN-LAST:event_btnBoldActionPerformed
    //Just nu kan texten inte vara bold och italic samtidigt 
    //och allting i textarean blir kursivt
    private void btnItalicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItalicActionPerformed

        if (btnItalic.isSelected()) {
            tpInlagg.setFont(tpInlagg.getFont().deriveFont(Font.ITALIC));

            

        } else {
            tpInlagg.setFont(tpInlagg.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_btnItalicActionPerformed

    private void tfRubrikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfRubrikMouseClicked
        tfRubrik.setText(null);
    }//GEN-LAST:event_tfRubrikMouseClicked

    private void btnPubliceraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPubliceraActionPerformed
        String rubrik = tfRubrik.getText();
        String inlaggText = tpInlagg.getText();
        String kategori = cbKategori.getSelectedItem().toString();
        boolean utbildningVald = false;
        boolean forskningVald = false;
        int inlaggId = 0;
        String ingress = "";
        String[] textDelning = inlaggText.split(" ");
        Calendar dagensDatum = Calendar.getInstance();
        Date datum = dagensDatum.getTime();
        int forfattare = inloggadPerson.getId();

        if (textDelning.length > 14) {
            for (int i = 0; i < textDelning.length / 2 && i < 30; i++) {
                ingress = ingress + textDelning[i] + " ";
            }
            ingress = ingress + "...";
        } else {
            for (int i = 0; i < textDelning.length; i++) {
                ingress = ingress + textDelning[i] + " ";
            }
        }

        if (inlaggText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Du måste Skriva något!");
        } else {
            if (kategori == "Utbildning") {
                utbildningVald = true;
            } else if (kategori == "Forskning") {
                forskningVald = true;
            }
            if (utbildningVald || forskningVald) {
                try {
                    ResultSet idKoll = Database.sqlSelect("SELECT MAX(INLAGGID) FROM INLAGG"); //våran AutoIncrement ;D
                    if (idKoll.next()) {
                        inlaggId = idKoll.getInt(1) + 1;
                    }
                    Database.sqlInsert("insert into INLAGG (INLAGGID, RUBRIK, INGRESS, HELTEXT, FORFATTARE, FORSKNING, UTBILDNING, DATUM) values "
                            + " (" + inlaggId + ",'" + rubrik + "','" + ingress + "','" + inlaggText + "'," + forfattare + "," + forskningVald + "," + utbildningVald + ",'" + datum.toString() + "')");
                    JOptionPane.showMessageDialog(null, "Inlägget har publicerats");
                    dispose();

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Någonting gick fel!" + ex);
                }
    }//GEN-LAST:event_btnPubliceraActionPerformed
    else {
                JOptionPane.showMessageDialog(null, "Du måste välja en kategori!");
            }
        }
    }
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void cbStorlekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStorlekActionPerformed
        String font = cbFont.getSelectedItem().toString();
        String fontStorlek = cbStorlek.getSelectedItem().toString();

        int storlek2 = Integer.parseInt(fontStorlek);

        Font myFont = new Font(font, Font.PLAIN, storlek2);

        tpInlagg.setFont(myFont);
    }//GEN-LAST:event_cbStorlekActionPerformed

    private void cbFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFontActionPerformed
        String font = cbFont.getSelectedItem().toString();
        String fontStorlek = cbStorlek.getSelectedItem().toString();

        int storlek2 = Integer.parseInt(fontStorlek);

        Font myFont = new Font(font, Font.PLAIN, storlek2);

        tpInlagg.setFont(myFont);
    }//GEN-LAST:event_cbFontActionPerformed


    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBold;
    private javax.swing.JButton btnExit;
    private javax.swing.JToggleButton btnItalic;
    private javax.swing.JButton btnPublicera;
    private javax.swing.JComboBox<String> cbFont;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JComboBox<String> cbStorlek;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextField tfRubrik;
    private javax.swing.JTextPane tpInlagg;
    // End of variables declaration//GEN-END:variables
}
