/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import grupp1.Database;
import grupp1.Person;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.*;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.*;

/**
 *
 * @author Nötfärs
 */
public class KalenderGUI extends javax.swing.JFrame {
    
    private Person inloggadPerson;
    
    public KalenderGUI() {
        initComponents();
        this.inloggadPerson = inloggadPerson;
        Calendar cal = Calendar.getInstance();
        lblDatum.setText("Dagens datum är: " + cal.getTime().toString());
        uppdateraDatum();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlMeny = new javax.swing.JPanel();
        btnHem = new javax.swing.JButton();
        btnUtbildning = new javax.swing.JButton();
        btnForskning = new javax.swing.JButton();
        btnProfil = new javax.swing.JButton();
        lblDatum = new javax.swing.JLabel();
        pnlMeny2 = new javax.swing.JPanel();
        btnStartsida = new javax.swing.JButton();
        btnSkapaInlagg = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        pnlTextArea = new javax.swing.JPanel();
        pnlKalender = new javax.swing.JPanel();
        dateChooserPnl = new datechooser.beans.DateChooserPanel();
        pnlBokaMote = new javax.swing.JPanel();
        scrlPnlTidTill = new javax.swing.JScrollPane();
        jListTidTill = new javax.swing.JList<>();
        btnBokaMote = new javax.swing.JButton();
        scrlPnlBeskrivning = new javax.swing.JScrollPane();
        txtAreaBeskrivning = new javax.swing.JTextArea();
        lblValjTid = new javax.swing.JLabel();
        lblValjPerson = new javax.swing.JLabel();
        scrlPnlTidFran = new javax.swing.JScrollPane();
        jListTidFran = new javax.swing.JList<>();
        lblFran = new javax.swing.JLabel();
        lblTill = new javax.swing.JLabel();
        scrlPnlValjPerson = new javax.swing.JScrollPane();
        jListValjPerson = new javax.swing.JList<>();
        lblValtDatum = new javax.swing.JLabel();
        lblDatumet = new javax.swing.JLabel();
        lblBeskrivningOchMotesplats = new javax.swing.JLabel();
        lblValdaPersoner = new javax.swing.JLabel();
        scrlPnlValdPerson = new javax.swing.JScrollPane();
        jListValdPerson = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));

        btnHem.setBackground(new java.awt.Color(255, 255, 255));
        btnHem.setText("Hem");

        btnUtbildning.setBackground(new java.awt.Color(255, 255, 255));
        btnUtbildning.setText("Utbildning");

        btnForskning.setBackground(new java.awt.Color(255, 255, 255));
        btnForskning.setText("Forskning");
        btnForskning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForskningActionPerformed(evt);
            }
        });

        btnProfil.setBackground(new java.awt.Color(255, 255, 255));
        btnProfil.setText("Profil");
        btnProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenyLayout = new javax.swing.GroupLayout(pnlMeny);
        pnlMeny.setLayout(pnlMenyLayout);
        pnlMenyLayout.setHorizontalGroup(
            pnlMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHem, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUtbildning, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnForskning, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenyLayout.setVerticalGroup(
            pnlMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfil)
                    .addComponent(btnForskning)
                    .addComponent(btnUtbildning)
                    .addComponent(btnHem)
                    .addComponent(lblDatum))
                .addContainerGap())
        );

        btnStartsida.setBackground(new java.awt.Color(255, 255, 255));
        btnStartsida.setText("Startsida");
        btnStartsida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartsidaActionPerformed(evt);
            }
        });

        btnSkapaInlagg.setBackground(new java.awt.Color(255, 255, 255));
        btnSkapaInlagg.setText("Skapa inlägg");
        btnSkapaInlagg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaInlaggActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Tillbaka");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMeny2Layout = new javax.swing.GroupLayout(pnlMeny2);
        pnlMeny2.setLayout(pnlMeny2Layout);
        pnlMeny2Layout.setHorizontalGroup(
            pnlMeny2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMeny2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMeny2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSkapaInlagg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStartsida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMeny2Layout.setVerticalGroup(
            pnlMeny2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMeny2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStartsida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSkapaInlagg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );

        pnlTextArea.setLayout(new java.awt.CardLayout());

        pnlKalender.setBackground(new java.awt.Color(255, 255, 255));

        dateChooserPnl.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserPnl.setCalendarBackground(new java.awt.Color(255, 255, 255));
    dateChooserPnl.setWeekStyle(datechooser.view.WeekDaysStyle.FULL);
    dateChooserPnl.setLocale(new java.util.Locale("sv", "SE", ""));
    dateChooserPnl.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
        public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
            dateChooserPnlOnSelectionChange(evt);
        }
    });

    javax.swing.GroupLayout pnlKalenderLayout = new javax.swing.GroupLayout(pnlKalender);
    pnlKalender.setLayout(pnlKalenderLayout);
    pnlKalenderLayout.setHorizontalGroup(
        pnlKalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(dateChooserPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
    );
    pnlKalenderLayout.setVerticalGroup(
        pnlKalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(dateChooserPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
    );

    pnlTextArea.add(pnlKalender, "pnlKalender");

    jListTidTill.setModel(new javax.swing.AbstractListModel<String>() {
        String[] strings = { "00.00", "00.30", "01.00", "01.30", "02.00", "02.30", "03.00", "03.30", "04.00", "04.30", "05.30", "06.00", "06.30", "07.00", "07.30", "08.30", "09.00", "09.30", "10.00", "10.30", "11.00", "11.30", "12.00", "12.30", "13.00", "13.30", "14.00", "14.30", "15.00", "15.30", "16.00", "16.30", "17.00", "17.30", "18.00", "18.30", "19.00", "19.30", "20.00", "20.30", "21.00", "21.30", "22.00", "22.30", "23.00", "23.30" };
        public int getSize() { return strings.length; }
        public String getElementAt(int i) { return strings[i]; }
    });
    scrlPnlTidTill.setViewportView(jListTidTill);

    btnBokaMote.setText("Boka möte");

    txtAreaBeskrivning.setColumns(20);
    txtAreaBeskrivning.setRows(5);
    scrlPnlBeskrivning.setViewportView(txtAreaBeskrivning);

    lblValjTid.setText("Välj tid för mötet");

    lblValjPerson.setText("Bjud in deltagare");

    jListTidFran.setModel(new javax.swing.AbstractListModel<String>() {
        String[] strings = { "00.00", "00.30", "01.00", "01.30", "02.00", "02.30", "03.00", "03.30", "04.00", "04.30", "05.30", "06.00", "06.30", "07.00", "07.30", "08.30", "09.00", "09.30", "10.00", "10.30", "11.00", "11.30", "12.00", "12.30", "13.00", "13.30", "14.00", "14.30", "15.00", "15.30", "16.00", "16.30", "17.00", "17.30", "18.00", "18.30", "19.00", "19.30", "20.00", "20.30", "21.00", "21.30", "22.00", "22.30", "23.00", "23.30" };
        public int getSize() { return strings.length; }
        public String getElementAt(int i) { return strings[i]; }
    });
    scrlPnlTidFran.setViewportView(jListTidFran);

    lblFran.setText("Från");

    lblTill.setText("Till");

    jListValjPerson.setModel(new javax.swing.DefaultListModel<String>()
    );
    jListValjPerson.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            jListValjPersonFocusGained(evt);
        }
    });
    jListValjPerson.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jListValjPersonMouseClicked(evt);
        }
    });
    scrlPnlValjPerson.setViewportView(jListValjPerson);

    lblBeskrivningOchMotesplats.setText("Beskrivning och mötesplats");

    lblValdaPersoner.setText("Valda deltagare");

    jListValdPerson.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jListValdPersonMouseClicked(evt);
        }
    });
    scrlPnlValdPerson.setViewportView(jListValdPerson);

    javax.swing.GroupLayout pnlBokaMoteLayout = new javax.swing.GroupLayout(pnlBokaMote);
    pnlBokaMote.setLayout(pnlBokaMoteLayout);
    pnlBokaMoteLayout.setHorizontalGroup(
        pnlBokaMoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlBokaMoteLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnlBokaMoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scrlPnlValjPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblValjPerson)
                .addGroup(pnlBokaMoteLayout.createSequentialGroup()
                    .addGroup(pnlBokaMoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblValjTid)
                        .addGroup(pnlBokaMoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrlPnlTidFran, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFran)))
                    .addGap(18, 18, 18)
                    .addGroup(pnlBokaMoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scrlPnlTidTill, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTill))))
            .addGroup(pnlBokaMoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBokaMoteLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(pnlBokaMoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlBokaMoteLayout.createSequentialGroup()
                            .addComponent(lblValdaPersoner)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(pnlBokaMoteLayout.createSequentialGroup()
                            .addComponent(scrlPnlValdPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(78, 78, 78)
                            .addComponent(btnBokaMote)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBokaMoteLayout.createSequentialGroup()
                    .addGroup(pnlBokaMoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBokaMoteLayout.createSequentialGroup()
                            .addGap(214, 214, 214)
                            .addComponent(lblBeskrivningOchMotesplats))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBokaMoteLayout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(lblDatumet, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBokaMoteLayout.createSequentialGroup()
                    .addGap(183, 183, 183)
                    .addComponent(scrlPnlBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 28, Short.MAX_VALUE))))
        .addGroup(pnlBokaMoteLayout.createSequentialGroup()
            .addGap(302, 302, 302)
            .addComponent(lblValtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    pnlBokaMoteLayout.setVerticalGroup(
        pnlBokaMoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlBokaMoteLayout.createSequentialGroup()
            .addGroup(pnlBokaMoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(pnlBokaMoteLayout.createSequentialGroup()
                    .addGroup(pnlBokaMoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlBokaMoteLayout.createSequentialGroup()
                            .addComponent(lblValtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblDatumet, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBokaMoteLayout.createSequentialGroup()
                            .addComponent(lblValjTid)
                            .addGap(25, 25, 25)))
                    .addComponent(lblBeskrivningOchMotesplats)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(scrlPnlBeskrivning, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addGroup(pnlBokaMoteLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(pnlBokaMoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTill)
                        .addComponent(lblFran))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnlBokaMoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(scrlPnlTidTill, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(scrlPnlTidFran))))
            .addGap(16, 16, 16)
            .addGroup(pnlBokaMoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(pnlBokaMoteLayout.createSequentialGroup()
                    .addGroup(pnlBokaMoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblValdaPersoner)
                        .addComponent(lblValjPerson))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnlBokaMoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(scrlPnlValjPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(scrlPnlValdPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(btnBokaMote))
            .addGap(19, 19, 19))
    );

    pnlTextArea.add(pnlBokaMote, "pnlBokaMote");

    javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
    pnlMain.setLayout(pnlMainLayout);
    pnlMainLayout.setHorizontalGroup(
        pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(pnlMeny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createSequentialGroup()
                    .addComponent(pnlMeny2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(pnlTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    pnlMainLayout.setVerticalGroup(
        pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlMainLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(pnlMeny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlMeny2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        getLayout("pnlKalender");
        DefaultListModel emptyModel = new DefaultListModel();
        jListValdPerson.setModel(emptyModel);
        jListValjPerson.setModel(emptyModel);
        txtAreaBeskrivning.setText("");
        jListTidFran.clearSelection();
        jListTidTill.clearSelection();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSkapaInlaggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaInlaggActionPerformed
        InlaggGUI inlagg = new InlaggGUI(inloggadPerson);
        inlagg.setVisible(true);
    }//GEN-LAST:event_btnSkapaInlaggActionPerformed

    private void btnStartsidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartsidaActionPerformed

    }//GEN-LAST:event_btnStartsidaActionPerformed

    private void btnProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilActionPerformed
        
        ProfilGUI pGUI = new ProfilGUI(inloggadPerson);
        pGUI.setVisible(true);

        //        try {
        //            Connection con = Database.getDB();
        //            Statement stmt = con.createStatement();
        //            String sql = "SELECT * FROM namn";
        //            ResultSet rs = stmt.executeQuery(sql);
        //            String p = "";
        //
        //            while (rs.next()) {
        //                p = p + "ID: " + rs.getInt("ID") + " - Namn: " + rs.getString("fornamn") + " " + rs.getString("efternamn") + "\n";
        //                jTextArea1.setText(p);
        //            }
        //        } catch (SQLException error) {
        //            System.out.println(error.getMessage());
        //        }
    }//GEN-LAST:event_btnProfilActionPerformed

    private void btnForskningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForskningActionPerformed

    }//GEN-LAST:event_btnForskningActionPerformed

    private void dateChooserPnlOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dateChooserPnlOnSelectionChange
        getLayout("pnlBokaMote");
        lblValtDatum.setText("Valt datum är:");
        String datum = dateChooserPnl.getSelectedDate().getTime().toString();
        String subDatum = datum.substring(0, 11) + "," + datum.substring(24, 28);
        lblDatumet.setText(subDatum);
        DefaultListModel listModel = new DefaultListModel();
        try {
            ResultSet namnLista = Database.sqlSelect("SELECT F_NAMN, E_NAMN FROM ANVANDARE");
            while (namnLista.next()) {
                listModel.addElement(namnLista.getString("F_NAMN") + " " + namnLista.getString("E_NAMN"));
            }
            jListValjPerson.setModel(listModel);
        } catch (SQLException SQLError) {
            
        }
        
    }//GEN-LAST:event_dateChooserPnlOnSelectionChange

    private void jListValjPersonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jListValjPersonFocusGained

    }//GEN-LAST:event_jListValjPersonFocusGained

    private void jListValjPersonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListValjPersonMouseClicked
        DefaultListModel listModelRight = new DefaultListModel();
        DefaultListModel listModelLeft = new DefaultListModel();
        int i = jListValdPerson.getModel().getSize();
        int o = jListValjPerson.getModel().getSize();
        int taBort = jListValjPerson.getSelectedIndex();
        if (jListValjPerson.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Det finns inga mer personer att lägga till");
        }
        else {
        for (int a = 0; a < i; a++) {
            jListValdPerson.setSelectedIndex(a);
            String extraNamnRight = jListValdPerson.getSelectedValue();
            listModelRight.addElement(extraNamnRight);
            
        }
        String namn = jListValjPerson.getSelectedValue();
        listModelRight.addElement(namn);
        jListValdPerson.setModel(listModelRight);
        for (int a = 0; a < o; a++) {
            jListValjPerson.setSelectedIndex(a);
            String extraNamnLeft = jListValjPerson.getSelectedValue();
            listModelLeft.addElement(extraNamnLeft);
        }


        listModelLeft.removeElementAt(taBort);
        jListValjPerson.setModel(listModelLeft);
        
        }
    }//GEN-LAST:event_jListValjPersonMouseClicked

    private void jListValdPersonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListValdPersonMouseClicked
        DefaultListModel listModelRight = new DefaultListModel();
        DefaultListModel listModelLeft = new DefaultListModel();
        int i = jListValjPerson.getModel().getSize();
        int o = jListValdPerson.getModel().getSize();
        int taBort = jListValdPerson.getSelectedIndex();
        if (jListValdPerson.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Det finns inga mer personer att ta bort.");
        }
        else {
        for (int a = 0; a < i; a++) {
            jListValjPerson.setSelectedIndex(a);
            String extraNamnRight = jListValjPerson.getSelectedValue();
            listModelRight.addElement(extraNamnRight);
            
        }
        String namn = jListValdPerson.getSelectedValue();
        listModelRight.addElement(namn);
        jListValjPerson.setModel(listModelRight);
        for (int a = 0; a < o; a++) {
            jListValdPerson.setSelectedIndex(a);
            String extraNamnLeft = jListValdPerson.getSelectedValue();
            listModelLeft.addElement(extraNamnLeft);
        }


        listModelLeft.removeElementAt(taBort);
        jListValdPerson.setModel(listModelLeft);
        }
    }//GEN-LAST:event_jListValdPersonMouseClicked
    public void uppdateraDatum() {
        ActionListener uppgift = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                Calendar cal = Calendar.getInstance();
                lblDatum.setText("Visar: Startsida - Dagens datum är: " + cal.getTime().toString());
                
            }
        };
        new Timer(1000, uppgift).start();
    }

    public void getLayout(String panelName) {//Denna metods jobb är att initialisera, och visa olika containers beroende på vilken funktion/knapp som användaren vill utnyttja.
        //Metoden tar endast emot containerns/panelens namn - och visar den.
        CardLayout card = (CardLayout) pnlTextArea.getLayout();
        card.show(pnlTextArea, panelName);
        
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBokaMote;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnForskning;
    private javax.swing.JButton btnHem;
    private javax.swing.JButton btnProfil;
    private javax.swing.JButton btnSkapaInlagg;
    private javax.swing.JButton btnStartsida;
    private javax.swing.JButton btnUtbildning;
    private datechooser.beans.DateChooserPanel dateChooserPnl;
    private javax.swing.JList<String> jListTidFran;
    private javax.swing.JList<String> jListTidTill;
    private javax.swing.JList<String> jListValdPerson;
    private javax.swing.JList<String> jListValjPerson;
    private javax.swing.JLabel lblBeskrivningOchMotesplats;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblDatumet;
    private javax.swing.JLabel lblFran;
    private javax.swing.JLabel lblTill;
    private javax.swing.JLabel lblValdaPersoner;
    private javax.swing.JLabel lblValjPerson;
    private javax.swing.JLabel lblValjTid;
    private javax.swing.JLabel lblValtDatum;
    private javax.swing.JPanel pnlBokaMote;
    private javax.swing.JPanel pnlKalender;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMeny;
    private javax.swing.JPanel pnlMeny2;
    private javax.swing.JPanel pnlTextArea;
    private javax.swing.JScrollPane scrlPnlBeskrivning;
    private javax.swing.JScrollPane scrlPnlTidFran;
    private javax.swing.JScrollPane scrlPnlTidTill;
    private javax.swing.JScrollPane scrlPnlValdPerson;
    private javax.swing.JScrollPane scrlPnlValjPerson;
    private javax.swing.JTextArea txtAreaBeskrivning;
    // End of variables declaration//GEN-END:variables
}
