/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import grupp1.Database;
import grupp1.Person;
import java.awt.Image;
import java.sql.ResultSet;
import javax.swing.ImageIcon;

/**
 *
 * @author itslo
 */
public class RedigeraProfilGUI extends javax.swing.JFrame {

    private Person personen;

    /**
     * Creates new form RedigeraProfilGUI
     */
    public RedigeraProfilGUI(Person personen) {
        this.personen = personen;
        initComponents();
        ResultSet rs = Database.sqlFraga("select FOTO from bilder where personid = " + personen.getId());
        try {
            if (rs.next()) {
                byte[] img = rs.getBytes("FOTO");
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImg = im.getScaledInstance(lblBild.getWidth(), lblBild.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImg);
                lblBild.setIcon(newImage);
            }
        } catch (Exception error) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pAndraBild = new javax.swing.JPanel();
        lblBild = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAndraBeskrivning = new javax.swing.JTextArea();
        pAndraInfo = new javax.swing.JPanel();
        lblTelefon = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblRum = new javax.swing.JLabel();
        tfAndraTele = new javax.swing.JTextField();
        tfAndraEpost = new javax.swing.JTextField();
        tfAndraRum = new javax.swing.JTextField();
        btnAndra = new javax.swing.JButton();
        btnNyProfilB = new javax.swing.JButton();
        btnAndraBeskriv = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pAndraBild.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pAndraBildLayout = new javax.swing.GroupLayout(pAndraBild);
        pAndraBild.setLayout(pAndraBildLayout);
        pAndraBildLayout.setHorizontalGroup(
            pAndraBildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );
        pAndraBildLayout.setVerticalGroup(
            pAndraBildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        );

        taAndraBeskrivning.setColumns(20);
        taAndraBeskrivning.setRows(5);
        jScrollPane1.setViewportView(taAndraBeskrivning);

        pAndraInfo.setBackground(new java.awt.Color(255, 255, 255));

        lblTelefon.setText("Telefon:");

        lblEpost.setText("E-post:");

        lblRum.setText("Rum:");

        tfAndraTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAndraTeleActionPerformed(evt);
            }
        });

        btnAndra.setBackground(new java.awt.Color(255, 255, 255));
        btnAndra.setText("Ändra");
        btnAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pAndraInfoLayout = new javax.swing.GroupLayout(pAndraInfo);
        pAndraInfo.setLayout(pAndraInfoLayout);
        pAndraInfoLayout.setHorizontalGroup(
            pAndraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAndraInfoLayout.createSequentialGroup()
                .addGroup(pAndraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAndraInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pAndraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEpost)
                            .addGroup(pAndraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pAndraInfoLayout.createSequentialGroup()
                                    .addComponent(lblRum)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                    .addComponent(tfAndraRum, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pAndraInfoLayout.createSequentialGroup()
                                    .addComponent(lblTelefon)
                                    .addGap(18, 18, 18)
                                    .addGroup(pAndraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfAndraEpost, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                        .addComponent(tfAndraTele))))))
                    .addGroup(pAndraInfoLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnAndra)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pAndraInfoLayout.setVerticalGroup(
            pAndraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAndraInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAndraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(tfAndraTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAndraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(tfAndraEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAndraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRum)
                    .addComponent(tfAndraRum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAndra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNyProfilB.setBackground(new java.awt.Color(255, 255, 255));
        btnNyProfilB.setText("Välj bild");
        btnNyProfilB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyProfilBActionPerformed(evt);
            }
        });

        btnAndraBeskriv.setBackground(new java.awt.Color(255, 255, 255));
        btnAndraBeskriv.setText("Ändra");

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Tillbaka till Profil");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNyProfilB)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pAndraBild, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pAndraInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                        .addComponent(btnAndraBeskriv)
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(pAndraInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pAndraBild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(btnNyProfilB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAndraBeskriv)
                    .addComponent(btnExit))
                .addGap(11, 11, 11))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfAndraTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAndraTeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAndraTeleActionPerformed

    private void btnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAndraActionPerformed

    private void btnNyProfilBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyProfilBActionPerformed
        Database.laggTillBild(personen);
    }//GEN-LAST:event_btnNyProfilBActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        ProfilGUI pGUI = new ProfilGUI(personen);
        pGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndra;
    private javax.swing.JButton btnAndraBeskriv;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNyProfilB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBild;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblRum;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JPanel pAndraBild;
    private javax.swing.JPanel pAndraInfo;
    private javax.swing.JTextArea taAndraBeskrivning;
    private javax.swing.JTextField tfAndraEpost;
    private javax.swing.JTextField tfAndraRum;
    private javax.swing.JTextField tfAndraTele;
    // End of variables declaration//GEN-END:variables
}
