/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import grupp1.Database;
import grupp1.Person;
import java.awt.Image;
import java.sql.ResultSet;
import javax.swing.ImageIcon;

/**
 *
 * @author itslo
 */
public class RedigeraProfilGUI extends javax.swing.JFrame {

    private Person inloggadPerson;

    /**
     * Creates new form RedigeraProfilGUI
     */
    public RedigeraProfilGUI(Person inloggadPerson) {
        this.inloggadPerson = inloggadPerson;
        initComponents();
        Database.uppdateraBild(lblBild, inloggadPerson);
        
        String beskrivning = inloggadPerson.getBeskrivning();
        taAndraBeskrivning.setText(beskrivning);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pAndraBild = new javax.swing.JPanel();
        lblBild = new javax.swing.JLabel();
        scrPnlTxtArea = new javax.swing.JScrollPane();
        taAndraBeskrivning = new javax.swing.JTextArea();
        pAndraInfo = new javax.swing.JPanel();
        lblTelefon = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblRum = new javax.swing.JLabel();
        tfAndraTele = new javax.swing.JTextField();
        tfAndraEpost = new javax.swing.JTextField();
        tfAndraRum = new javax.swing.JTextField();
        lblLosenOrd = new javax.swing.JLabel();
        tfLosenOrd = new javax.swing.JTextField();
        btnNyProfilB = new javax.swing.JButton();
        btnAndraBeskriv = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnAndra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pAndraBild.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pAndraBildLayout = new javax.swing.GroupLayout(pAndraBild);
        pAndraBild.setLayout(pAndraBildLayout);
        pAndraBildLayout.setHorizontalGroup(
            pAndraBildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pAndraBildLayout.setVerticalGroup(
            pAndraBildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        );

        taAndraBeskrivning.setColumns(20);
        taAndraBeskrivning.setRows(5);
        scrPnlTxtArea.setViewportView(taAndraBeskrivning);

        pAndraInfo.setBackground(new java.awt.Color(255, 255, 255));

        lblTelefon.setText("Telefon:");

        lblEpost.setText("E-post:");

        lblRum.setText("Rum:");

        tfAndraTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAndraTeleActionPerformed(evt);
            }
        });

        lblLosenOrd.setText("Nytt lösenord");

        javax.swing.GroupLayout pAndraInfoLayout = new javax.swing.GroupLayout(pAndraInfo);
        pAndraInfo.setLayout(pAndraInfoLayout);
        pAndraInfoLayout.setHorizontalGroup(
            pAndraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAndraInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAndraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEpost)
                    .addGroup(pAndraInfoLayout.createSequentialGroup()
                        .addComponent(lblRum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(tfAndraRum, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pAndraInfoLayout.createSequentialGroup()
                        .addComponent(lblTelefon)
                        .addGap(18, 18, 18)
                        .addGroup(pAndraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfAndraEpost, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(tfAndraTele)))
                    .addGroup(pAndraInfoLayout.createSequentialGroup()
                        .addComponent(lblLosenOrd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLosenOrd)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pAndraInfoLayout.setVerticalGroup(
            pAndraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAndraInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAndraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(tfAndraTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAndraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(tfAndraEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAndraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRum)
                    .addComponent(tfAndraRum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(pAndraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenOrd)
                    .addComponent(tfLosenOrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnNyProfilB.setBackground(new java.awt.Color(255, 255, 255));
        btnNyProfilB.setText("Välj bild");
        btnNyProfilB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyProfilBActionPerformed(evt);
            }
        });

        btnAndraBeskriv.setBackground(new java.awt.Color(255, 255, 255));
        btnAndraBeskriv.setText("Ändra");

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Tillbaka till Profil");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnAndra.setBackground(new java.awt.Color(255, 255, 255));
        btnAndra.setText("Ändra");
        btnAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrPnlTxtArea)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNyProfilB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAndra)
                                .addGap(48, 48, 48))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pAndraBild, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pAndraInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                        .addComponent(btnAndraBeskriv)
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(pAndraBild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(pAndraInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNyProfilB)
                    .addComponent(btnAndra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrPnlTxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAndraBeskriv)
                    .addComponent(btnExit))
                .addGap(11, 11, 11))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfAndraTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAndraTeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAndraTeleActionPerformed

    private void btnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAndraActionPerformed

    private void btnNyProfilBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyProfilBActionPerformed
        if (Database.laggTillBild(inloggadPerson)) {
            Database.uppdateraBild(lblBild, inloggadPerson);
    }    
    }//GEN-LAST:event_btnNyProfilBActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        ProfilGUI pGUI = new ProfilGUI(inloggadPerson);
        pGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndra;
    private javax.swing.JButton btnAndraBeskriv;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNyProfilB;
    private javax.swing.JLabel lblBild;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblLosenOrd;
    private javax.swing.JLabel lblRum;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JPanel pAndraBild;
    private javax.swing.JPanel pAndraInfo;
    private javax.swing.JScrollPane scrPnlTxtArea;
    private javax.swing.JTextArea taAndraBeskrivning;
    private javax.swing.JTextField tfAndraEpost;
    private javax.swing.JTextField tfAndraRum;
    private javax.swing.JTextField tfAndraTele;
    private javax.swing.JTextField tfLosenOrd;
    // End of variables declaration//GEN-END:variables
}
